In [1]:
import tensorflow as tf

# Tensorfllow

In [2]:
tf.ones(shape = (2, 1))

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>

In [4]:
x = tf.random.normal(shape = (3, 1), mean = 0., stddev = 1.)
x

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[-0.16457614],
       [-1.0653929 ],
       [ 0.21694137]], dtype=float32)>

In [5]:
x = tf.random.uniform(shape = (3, 1), minval = 0., maxval = 1.)
x

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[0.11125183],
       [0.23262215],
       [0.76196504]], dtype=float32)>

In [8]:
x = tf.ones(shape=(2, 2))

# Tensors are constants, this will error
# x[0, 0] = 0

In [10]:
v = tf.Variable(initial_value=tf.random.normal(shape=(3, 1)))
v

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-1.0970312 ],
       [-0.28910193],
       [-0.35856408]], dtype=float32)>

In [12]:
v.assign(tf.ones((3,1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>

## Dense layer in TF

In [13]:
def dense(inputs, W, b):
    return tf.nn.relu(tf.matmul(inputs, W) + b)

## GradientTape

In [54]:
input_var = tf.Variable(2.5)
with tf.GradientTape() as tape:
    result = input_var ** 2
gradient = tape.gradient(result, input_var)

# y = x ** 2
# y' = 2x
# y' = 2 * 2.5
# y' = 5.0

gradient.numpy()

np.float32(5.0)

In [27]:
# With constants, need tape.watch()
input_const = tf.constant(3.0)
with tf.GradientTape() as tape:
    tape.watch(input_const)
    result = tf.square(input_const)
gradient = tape.gradient(result, input_const)
gradient

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>